# Імпорт модулів

In [1]:
import numpy as np
import pandas as pd

# Завантаження файлу даних

In [2]:
df = pd.read_csv("2017_jun_final.csv")

## Вивести перші рядки таблиці за допомогою методу `head`

In [3]:
df.head()

,N,Должность,Язык.программирования,Специализация,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,...,Еще.студент,Уровень.английского,Предметная.область,Дата.заполнения,User.Agent,exp,current_job_exp,salary,Валюта,cls
0,1,Junior QA engineer,NaN,Manual QA,0.5,0.5,400,0,Харьков,до 10 человек,...,True,ниже среднего,"iOS,eCommerce",12/06/2017 12:38:08,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN,QA
1,2,Junior QA engineer,NaN,Manual QA,меньше 3 месяцев,меньше 3 месяцев,430,130,Харьков,свыше 1000 человек,...,True,выше среднего,Веб-разработка,12/06/2017 12:42:51,Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...,0.0,0.0,430,NaN,QA
2,3,Software Engineer,C#/.NET,NaN,4,1,2500,800,Киев,до 1000 человек,...,False,средний,"Веб-разработка,Корпоративные системы",12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500,NaN,DEV
3,4,Software Engineer,JavaScript,NaN,5,4,2000,400,Одесса,до 200 человек,...,False,ниже среднего,"Desktop Applications,Веб-разработка",12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000,NaN,DEV
4,5,Senior Software Engineer,JavaScript,NaN,10 и более лет,0.5,4500,500,Другой,до 10 человек,...,False,средний,"Desktop Applications,Веб-разработка",12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500,NaN,DEV

## Визначте кількість рядків та стовпців у датафреймі

In [4]:
rows, columns = df.shape
print("Чмсло рядків: ", rows)
print("Число стовбців: ", columns)

Чмсло рядків:  8704
Число стовбців:  25

## Замініть у таблиці значення "—" на значення NaN

In [5]:
REPALACE_SYMBOL = '—'
if REPALACE_SYMBOL in df.values:
    # Если есть "-", замените их на NaN и выведите количество замен
    df.replace(REPALACE_SYMBOL, np.nan, inplace=True)
    count_replacements = df.isna().sum()
    print("Кількість замін:", count_replacements)
else:
    print(f"У DataFrame немає {REPALACE_SYMBOL} для заміни.")

У DataFrame немає — для заміни.

## Визначте типи всіх стовпців за допомогою `dataframe.dtypes`

In [6]:
column_types = df.dtypes
print(column_types)

N                                     int64
Должность                            object
Язык.программирования                object
Специализация                        object
Общий.опыт.работы                    object
Опыт.работы.на.текущем.месте         object
Зарплата.в.месяц                      int64
Изменение.зарплаты.за.12.месяцев      int64
Город                                object
Размер.компании                      object
Тип.компании                         object
Пол                                  object
Возраст                               int64
Образование                          object
Университет                          object
Еще.студент                            bool
Уровень.английского                  object
Предметная.область                   object
Дата.заполнения                      object
User.Agent                           object
exp                                 float64
current_job_exp                     float64
salary                                int64
Валюта                               object
cls                                  object
dtype: object

## Замініть типи нечислових колонок на числові. Підказка - це колонки, де знаходився символ "—"

In [7]:
# ? Так немає ж. або замінені в попередньому завданні

## Порахуйте, яка частка пропусків міститься в кожній колонці (використовуйте методи `isnull` та `sum`)

In [8]:
missing_percentage = df.isnull().mean().round(2) * 100
print(missing_percentage)

N                                     0.0
Должность                             0.0
Язык.программирования                44.0
Специализация                        83.0
Общий.опыт.работы                     0.0
Опыт.работы.на.текущем.месте          0.0
Зарплата.в.месяц                      0.0
Изменение.зарплаты.за.12.месяцев      0.0
Город                                 0.0
Размер.компании                       0.0
Тип.компании                          0.0
Пол                                   0.0
Возраст                               0.0
Образование                           0.0
Университет                           4.0
Еще.студент                           0.0
Уровень.английского                   0.0
Предметная.область                    3.0
Дата.заполнения                       0.0
User.Agent                            0.0
exp                                   0.0
current_job_exp                       0.0
salary                                0.0
Валюта                              100.0
cls                                  18.0
dtype: float64

## Видаліть усі стовпці з пропусками, крім стовпця "Мова програмування"

In [32]:
column_to_keep = df['Язык.программирования']
df_1 = df.dropna(axis=1, how='any')
df_1 = df_1.assign(**{'Язык.программирования': column_to_keep})
df_1

,N,Должность,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,Тип.компании,Пол,Возраст,Образование,Еще.студент,Уровень.английского,Дата.заполнения,User.Agent,exp,current_job_exp,salary,Язык.программирования
0,1,Junior QA engineer,0.5,0.5,400,0,Харьков,до 10 человек,Аутсорсинговая,женский,20,Незаконченное высшее,True,ниже среднего,12/06/2017 12:38:08,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN
1,2,Junior QA engineer,меньше 3 месяцев,меньше 3 месяцев,430,130,Харьков,свыше 1000 человек,Аутсорсинговая,женский,21,Незаконченное высшее,True,выше среднего,12/06/2017 12:42:51,Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...,0.0,0.0,430,NaN
2,3,Software Engineer,4,1,2500,800,Киев,до 1000 человек,Аутсорсинговая,мужской,26,Высшее,False,средний,12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500,C#/.NET
3,4,Software Engineer,5,4,2000,400,Одесса,до 200 человек,Продуктовая,мужской,30,Среднее,False,ниже среднего,12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000,JavaScript
4,5,Senior Software Engineer,10 и более лет,0.5,4500,500,Другой,до 10 человек,Продуктовая,мужской,30,Техникум / Колледж,False,средний,12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500,JavaScript
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8699,8700,QA engineer,1,меньше 3 месяцев,700,700,Одесса,до 50 человек,Аутсорсинговая,мужской,23,Высшее,False,средний,12/07/2017 15:45:24,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....,1.0,0.0,700,NaN
8700,8701,Marketing,0.5,0.5,400,120,Киев,до 50 человек,Продуктовая,женский,22,Высшее,False,ниже среднего,12/07/2017 17:00:06,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN
8701,8702,Junior Software Engineer,1,0.5,800,500,Львов,до 10 человек,Аутстаффинговая,мужской,30,Незаконченное высшее,False,выше среднего,12/07/2017 17:32:26,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,0.5,800,Ruby/Rails
8702,8703,Team lead,6,4,2600,0,Днепр,свыше 1000 человек,Аутсорсинговая,мужской,34,Высшее,False,продвинутый,12/07/2017 18:14:59,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,6.0,4.0,2600,NaN
8703,8704,Senior Software Engineer,7,2,5000,800,Одесса,до 1000 человек,Продуктовая,мужской,28,Высшее,False,выше среднего,12/07/2017 21:28:57,Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X...,7.0,2.0,5000,Java

## Знову порахуйте, яка частка пропусків міститься в кожній колонці і переконайтеся, що залишився тільки стовпець "Мова.програмування"

In [33]:
missing_percentage = df_1.isnull().mean().round(2) * 100
print(missing_percentage)

N                                    0.0
Должность                            0.0
Общий.опыт.работы                    0.0
Опыт.работы.на.текущем.месте         0.0
Зарплата.в.месяц                     0.0
Изменение.зарплаты.за.12.месяцев     0.0
Город                                0.0
Размер.компании                      0.0
Тип.компании                         0.0
Пол                                  0.0
Возраст                              0.0
Образование                          0.0
Еще.студент                          0.0
Уровень.английского                  0.0
Дата.заполнения                      0.0
User.Agent                           0.0
exp                                  0.0
current_job_exp                      0.0
salary                               0.0
Язык.программирования               44.0
dtype: float64

## Видаліть усі рядки у вихідній таблиці за допомогою методу `dropna`

In [34]:
df.dropna()

,N,Должность,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,Тип.компании,Пол,Возраст,Образование,Еще.студент,Уровень.английского,Дата.заполнения,User.Agent,exp,current_job_exp,salary,Язык.программирования
2,3,Software Engineer,4,1,2500,800,Киев,до 1000 человек,Аутсорсинговая,мужской,26,Высшее,False,средний,12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500,C#/.NET
3,4,Software Engineer,5,4,2000,400,Одесса,до 200 человек,Продуктовая,мужской,30,Среднее,False,ниже среднего,12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000,JavaScript
4,5,Senior Software Engineer,10 и более лет,0.5,4500,500,Другой,до 10 человек,Продуктовая,мужской,30,Техникум / Колледж,False,средний,12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500,JavaScript
6,7,Junior Software Engineer,1,меньше 3 месяцев,600,100,Хмельницкий,до 50 человек,Аутсорсинговая,мужской,23,Высшее,False,ниже среднего,12/06/2017 13:04:26,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.0,0.0,600,C#/.NET
7,8,Senior Software Engineer,6,1,3300,500,Киев,до 10 человек,Продуктовая,мужской,28,Высшее,False,выше среднего,12/06/2017 13:04:27,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,6.0,1.0,3300,C++
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8692,8693,Software Engineer,5,1,3500,650,Удаленно,до 200 человек,Аутсорсинговая,женский,28,Высшее,False,средний,12/07/2017 13:26:49,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,5.0,1.0,3500,Java
8694,8695,Junior Software Engineer,1,1,550,550,Харьков,до 200 человек,Аутсорсинговая,мужской,23,Высшее,False,ниже среднего,12/07/2017 14:14:33,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) ...,1.0,1.0,550,C#/.NET
8695,8696,Software Engineer,1,0.5,1500,1000,Киев,до 10 человек,Стартап,мужской,29,Высшее,False,средний,12/07/2017 14:39:21,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,0.5,1500,Python
8701,8702,Junior Software Engineer,1,0.5,800,500,Львов,до 10 человек,Аутстаффинговая,мужской,30,Незаконченное высшее,False,выше среднего,12/07/2017 17:32:26,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,0.5,800,Ruby/Rails
8703,8704,Senior Software Engineer,7,2,5000,800,Одесса,до 1000 человек,Продуктовая,мужской,28,Высшее,False,выше среднего,12/07/2017 21:28:57,Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X...,7.0,2.0,5000,Java